### ISSUE TITLE
License

### ISSUE THREAD

**Issue by esbullington** [yushih/simple-catenable-deque#1]
Hi, very cool project. I have a dataviz background and really like the visualization. 

Question: is the MIT license in this project's `package.json` correct? I need a purely functional deque for a ReasonML project, and don't have the Okasaki book (it's on my list of things to buy). So if the `Deque.ml` in this project is indeed open source under MIT, I'd like to just use it.

Thanks!

**Comment by yushih** [comment]
Sorry for the delay. I think there should be no problem because `Deque.ml` is not verbatim copy from the book.
